package ru.beywer.vaadin.designe;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

import fi.jasoft.dragdroplayouts.DDHorizontalSplitPanel;
import fi.jasoft.dragdroplayouts.DDTabSheet;
import fi.jasoft.dragdroplayouts.DDVerticalLayout;
import fi.jasoft.dragdroplayouts.client.ui.LayoutDragMode;

@SuppressWarnings("serial")
public class MainPage extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		DDHorizontalSplitPanel splitPanel = new DDHorizontalSplitPanel();
		splitPanel.setSizeFull();
		mainLayout.addComponent(splitPanel);
		splitPanel.setDragMode(LayoutDragMode.NONE);
		splitPanel.setDropHandler(new MyHorizontalSplitPanelDropHandler());
		splitPanel.setSplitPosition(25, Unit.PERCENTAGE);
		
		DDHorizontalSplitPanel internalSplitPanel = new DDHorizontalSplitPanel();
		internalSplitPanel.setSizeFull();
		internalSplitPanel.setDragMode(LayoutDragMode.NONE);
		internalSplitPanel.setDropHandler(new MyHorizontalSplitPanelDropHandler());
		internalSplitPanel.setSplitPosition(70f, Unit.PERCENTAGE);

		Button button1 = new Button("Buttka1");
		Button button2 = new Button("Buttka2");
		Button button3 = new Button("Buttka3");
		
		RichTextArea richTextArea = new RichTextArea();
		richTextArea.setSizeFull();
		final TextArea textArea = new TextArea();
		textArea.setSizeFull();
		
		DDVerticalLayout verticalLayout1 = new DDVerticalLayout();
		verticalLayout1.setDragMode(LayoutDragMode.NONE);	
		DDVerticalLayout verticalLayout2 = new DDVerticalLayout();
		verticalLayout1.setDragMode(LayoutDragMode.NONE);	
		DDVerticalLayout verticalLayout3 = new DDVerticalLayout();
		verticalLayout3.setDragMode(LayoutDragMode.NONE);	
		
		MyTabSheetDropHandler tabSheetDropHandler = new MyTabSheetDropHandler();
		DDTabSheet tabSheet1 = new DDTabSheet();
		tabSheet1.setSizeFull();
		tabSheet1.setDragMode(LayoutDragMode.CLONE_OTHER);
		tabSheet1.setDropHandler(tabSheetDropHandler);
		tabSheet1.addTab(button1, "Buttka1");
		tabSheet1.addTab(button2, "Buttka2");
		
		final DDTabSheet tabSheet2 = new DDTabSheet();
		tabSheet2.setSizeFull();
		tabSheet2.setDragMode(LayoutDragMode.CLONE_OTHER);
		tabSheet2.setDropHandler(tabSheetDropHandler);
		tabSheet2.addTab(button3, "Buttka3");
		tabSheet2.setImmediate(true);
		
		DDTabSheet tabSheet3 = new DDTabSheet();
		tabSheet3.setSizeFull();
		tabSheet3.setDragMode(LayoutDragMode.CLONE_OTHER);
		tabSheet3.setDropHandler(tabSheetDropHandler);
		tabSheet3.addTab(textArea, "Code");
		
		DDTabSheet tabSheet4 = new DDTabSheet();
		tabSheet4.setSizeFull();
		tabSheet4.setDragMode(LayoutDragMode.CLONE_OTHER);
		tabSheet4.setDropHandler(tabSheetDropHandler);
		tabSheet4.addTab(richTextArea, "UltraCode");

		Panel panel1 = new Panel(tabSheet1);
		panel1.setSizeFull();
		Panel panel2 = new Panel(tabSheet2);
		panel2.setSizeFull();
		Panel panel3 = new Panel(tabSheet3);
		panel3.setSizeFull();
		Panel panel4 = new Panel(tabSheet4);
		panel4.setSizeFull();
		
		verticalLayout1.setSizeFull();
		verticalLayout1.setSpacing(true);
		verticalLayout1.setMargin(true);
		verticalLayout1.addComponent(panel1);
		verticalLayout1.addComponent(panel2);

		verticalLayout2.setSizeFull();
		verticalLayout2.setSpacing(true);
		verticalLayout2.setMargin(true);
		verticalLayout2.addComponent(panel3);
		
		verticalLayout3.setSizeFull();
		verticalLayout3.setSpacing(true);
		verticalLayout3.setMargin(true);
		verticalLayout3.addComponent(panel4);
		
		splitPanel.addComponent(verticalLayout1);
		splitPanel.addComponent(internalSplitPanel);
		internalSplitPanel.addComponent(verticalLayout2);
		internalSplitPanel.addComponent(verticalLayout3);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		return mainLayout;
	}

}
