package ru.smartsolutions.mesgi.ru.smartsolutions.mesgi.nodelist;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class MainPage extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		TextArea textArea = new TextArea();
		textArea.setSizeFull();
		textArea.setValue("Test text");
		NodeHandler.setTextArea(textArea);
		
		mainLayout.addComponent(textArea);
	}

	@AutoGenerated
	private void buildMainLayout() {
			mainLayout = new VerticalLayout();
			mainLayout.setImmediate(false);
			mainLayout.setWidth("60%");
			mainLayout.setHeight("60%");
			mainLayout.setMargin(true);
			
			setWidth("100.0%");
			setHeight("100.0%");
	}

}
