package ru.beywer.vaadin.ru.beywer.vaadin.consoleecho;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;

@SuppressWarnings("serial")
public class MainPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Button button_1;

	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		
		PrintStream std = System.out;
		PrintStreamCapturer streamCapturer = new PrintStreamCapturer(textArea_1, std);
		System.setOut(streamCapturer);
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		mainLayout.addComponent(verticalSplitPanel_1);
		mainLayout.setExpandRatio(verticalSplitPanel_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("600px");
		verticalSplitPanel_1.setHeight("600px");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Print to TextArea and Karaf");
		button_1.setImmediate(true);
		button_1.setWidth("100.0%");
		button_1.setHeight("100.0%");
		verticalSplitPanel_1.addComponent(button_1);
		button_1.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				System.out.println("НИЧОСИ");
				System.out.println(123);
				System.out.println(123.5f);
				System.out.print("Привет, Мирище!!!  ");
				System.out.println(277.5d);
			}
		});
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("100.0%");
		textArea_1.setHeight("100.0%");
		verticalSplitPanel_1.addComponent(textArea_1);
		
		return verticalSplitPanel_1;
	}

}
