package ru.beywer.vaadin.ru.beywer.vaadin.consoleecho;

import java.io.PrintStream;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;

@SuppressWarnings("serial")
public class MainPage extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	private Panel panel_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button button_1;
	public MainPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
//		verticalLayout_3.addComponent(new Label("labelka"));
		
		PrintStream std = System.out;
		PrintStreamCapturer streamCapturer = new PrintStreamCapturer(panel_2, std);
		System.setOut(streamCapturer);
		
		for(int i =0; i < 25; i++)
			verticalLayout_3.addComponent(new Label(String.valueOf(i)));
		
		button_1.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				System.out.println("\nНИЧОСИ!");
				System.out.println(true);
				System.out.print("Hello Мир!!  ");
				System.out.println(27.356f);
				System.out.println(125);
			}
		});
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		mainLayout.addComponent(verticalSplitPanel_1);
		mainLayout.setExpandRatio(verticalSplitPanel_1, 1.0f);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("600px");
		verticalSplitPanel_1.setHeight("600px");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Print to TextArea and Karaf");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		verticalSplitPanel_1.addComponent(button_1);
		
		// panel_2
		panel_2 = buildPanel_2();
		verticalSplitPanel_1.addComponent(panel_2);
		
		return verticalSplitPanel_1;
	}

	@AutoGenerated
	private Panel buildPanel_2() {
		// common part: create layout
		panel_2 = new Panel();
		panel_2.setImmediate(false);
		panel_2.setScrollTop(9999);
		panel_2.setWidth("100.0%");
		panel_2.setHeight("100.0%");
		
		// verticalLayout_3
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		panel_2.setContent(verticalLayout_3);
		
		return panel_2;
	}

}
